sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: ./gradlew --version

script:
  - ./gradlew -DbuildVersion=travis-${TRAVIS_JOB_ID} clean build
  - ./gradlew asciidoctor scaladoc
  - ./gradlew skysail.server:export.server.int
  - ./gradlew skysail.server.demo:export.server.demo
  - ./gradlew copyConf copyRunnables

after_success:
  - docker --version
  - docker build -t evandor/skysail-server skysail.server/release
  - docker build -t evandor/skysail-server-demo skysail.server.demo/release
  - docker images
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/skysail-server:latest
  - docker push $DOCKER_USERNAME/skysail-server-demo:latest

#  - docker tag skysail-server $DOCKER_USERNAME/skysail-server

notifications:
    slack: skysail-io:QGRw4Q2CzA56P0c9p5M5xwlm
