sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: ./gradlew --version

script: ./gradlew clean build asciidoctor scaladoc skysail.server:export.server.int copyConf copyRunnables

after_success:
  - docker --version
  - docker build -t evandor/skysail-server skysail.server/release
  - docker images
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/skysail-server:latest

#  - docker tag skysail-server $DOCKER_USERNAME/skysail-server
