sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: ./gradlew --version

script: ./gradlew clean build asciidoctor scaladoc
script: ./gradlew skysail.server:export.server.int

after_success:
  - docker --version
  - docker build -t evandor/skysail-server skysail.server/release
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push evandor/skysail-server;
