sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: ./gradlew --version

script:
  - ./gradlew -DbuildVersion=travis-${TRAVIS_BUILD_NUMBER} clean build
  - ./gradlew asciidoctor scaladoc
  - ./gradlew skysail.server:export.server.docker
  - ./gradlew skysail.server.demo:export.server.demo.docker
  - ./gradlew skysail.server.seed:export.server.seed.docker
  - ./gradlew copyConf copyRunnables

after_success:
  - docker --version
  - docker build -t evandor/skysail-server skysail.server/release
  - docker build -t evandor/skysail-server-demo:${TRAVIS_BUILD_NUMBER} skysail.server.demo/release
  - docker build -t evandor/skysail-server-seed skysail.server.seed/release
  - docker images
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/skysail-server:latest
  - docker push $DOCKER_USERNAME/skysail-server-demo:${TRAVIS_BUILD_NUMBER}
  - docker push $DOCKER_USERNAME/skysail-server-seed:latest

#  - docker tag skysail-server $DOCKER_USERNAME/skysail-server

notifications:
    slack: skysail-io:QGRw4Q2CzA56P0c9p5M5xwlm
    webhooks:
      urls:
        - http://jenkins.twentyeleven.de/generic-webhook-trigger/invoke
      on_success: always # default: always
      on_failure: never # default: always
      on_cancel: never # default: always
      on_error: never # default: always