:source-highlighter: coderay
:imagesdir: images

= About skysail (server)
Carsten Gräf <evandor@gmail.com>
v0.0, 2017-11-04
:toc:


== Introduction: skysail...

...is: a *modular*, *domain-centric* and *RESTful BaaS* (Backend as a Service)

(that you can host yourself)

The overall goal of skysail is to provide you with an environment where you can
create typical backend logic in a generic, quick way with as little dependencies
as possible. This makes skysail suited for prototypes, first of all, but I hope
that this approach - even though very generic - is good enough for production
ready applications as well.

*Typical backend logic covered by skysail*:

* Authentication / Authorization
* Security aspects (like injections)
* Configuration
* Validation
* Documentation
* Persistence

We have some more things skysail could help you with:

* User Management
* HTML Rendering (Template Engine)
* Generic Client GUI
* Prototyping
* and - calling other APIs

A skysail backend does not only serve JSON to be used by some client, it creates
a generic web GUI so that you can actually use and validate your implementation
directly with a browser.

Please check this site for the current implementation status of the above
features (todo).

Now, let's explain the main buzz-words from the definition above:

=== Modularity
skysail is a collection of OSGi bundles, depending on other bundles, and
defining an API for domains like authentication, security, persistence and
so on. If some API implementation does not fulfil your needs, it is easy to
replace it with your own implementation.

=== Domain-Centric
skysail lets you concentrate on your business (or domain) logic. Http Server,
database, configuration setup and the like are already there. Just use them.
Or replace them with an implementation more suited for your needs.

=== RESTful
skysail concentrates on the backend and tries to stick to RESTful principles.

=== BaaS
skysail is a Backend-as-a-Service.

=== Self-Hosting
The difference to many other BaaS, you can download and run skysail on your
own machines.

== Why not use X/Y/Z?

Apart from being deployable as a *single jar* file, skysail supports *true modularity*.
That means, contrary to for example _Spring_, you have dynamic class and service
discovery, not just a static one (when the application is started). Replacing a
bundle with a new version or even a new implementation becomes trivial (apart
from writing the new bundle maybe ;)). The system can react to changes, which
could be a new additional bundle, or stopping a bundle, so that its services
will become unavailable.

== Getting started ...

to be done

== Terminology

This chapter provides a quick overview of the basic building block of a skysail installation.

=== skysail.server

This is the backbone of a skysail installation. It comes as a standalone executable jar or
as a docker container. Once started, it is ready to accept further bundles (called skysail
applications) with additional business logic to be installed and started on the fly.

skysail.server is a pure backend application, exposing only minimal functionality to clients
directly. Most of the available features are added using various skysail applications (or
combinations thereof).

=== skysail Applications

This is what you "put inside" of a skysail.server. A skysail application will provide
additional endpoints, serving various features depending on the nature of the application.

Technically, a skysail application is an OSGi bundle with an activator provding a specific
interface called _ApplicationProvider_.

=== Resources

A skysail application defines one or more _Resources_. A resource implements a specific
base class and wraps all business logic related to one or more http methods (like GET, POST, etc).

The idea is that this is the one and only place to implement business logic related to a
specific kind of request. For example, a simple CRUD implementation for a customer entity will
have a

* _PostCustomerResource_ - for creating a new customer and describing a customer entity
* _CustomersResource_ - for getting a list of customers
* _CustomerResource_ - getting and deleting a specific customer
* _PutCustomerResource_ - updating a customer entity

Details of this approach will be described in (todo)

[appendix]
=== Test

ss

=== Entities

A resource (as described above) is always related to an entity (or maybe value object). This
entity is the carrier of business data. An entity can contain other entities (or lists of them)
and be composed of other entites, making up complex data structures.

=== Routes

A route connects a path (like "/customer/4711") with a resource (like CustomerResource). This
mapping is used by the skysail server to redirect requests to the proper Resource (and find
appropriate paths given a resource class name).


== Concepts

include::concepts.adoc[leveloffset=+1]

== Resources

include::resources.adoc[leveloffset=+1]

== Request Processing

include::requestprocessing.adoc[leveloffset=+1]

== Domain and Business Logic

include::domainlogic.adoc[leveloffset=+1]

== Transformations

include::transformations.adoc[leveloffset=+1]

