:source-highlighter: coderay
:imagesdir: images

= skysail infrastructure
Carsten Gräf <evandor@gmail.com>
v0.0, 2017-11-12
:toc:


== Build

skysail is build with gradle, you can execute a build like this:

.gradle build using the provided gradle wrapper
[source,groovy]
gradlew clean build


== Build Systems

Currently, there are two build systems, jenkins@twentyeleven und Travis CI

=== Jenkins

Jenkins is using the multibranch pipeline plugin and evaluates the file
*Jenkinsfile_multibranch* from the root folder.

==== specific setup

In order to create docker images, the following change was made in /etc/sudoers using
sudo visudo:


./etc/sudoers
[source]
carsten ALL = NOPASSWD: /home/carsten/.hudson/jobs/skysail-server.multibranch/branches/release-0-0.6lhvn9/workspace/gradlew


=== Travis

== Monitoring

=== Graylog @ twentyeleven.de

Installation as in http://docs.graylog.org/en/2.3/pages/installation/operating_system_packages.html

sudo systemctl stop graylog-server
sudo vi /etc/graylog/server/server.conf
sudo systemctl start graylog-server
tail -f /var/log/graylog-server/server.log

http://log.skysail.io/