= all deployment / run modes

skysail projects can be started in a variety of ways:

== local IDE

=== Intellij

Below you'll find instructions for both Intellij and Eclipse.

==== OSGi BND run configuration

use server.website.ide.bndrun, using local configuration from /config/local

open http://localhost:8085

==== docker run configuration

Create a docker run configuration with a command like

'''
docker build -t <image_tag> .
&& docker run
-p 9102:9102
--name skysail-server-website-local
<image_tag>
'''

start, and open http://localhost:9102

Used configuration: from config/docker

=== Eclipse

to be done

== from jar file

./gradlew skysail.server.website:export.website
cd skysail.server.website/generated/distributions/executable/
java -jar website.jar

Configuration will be extracted from the contained server.website.jar file
and put next to the website.jar. Need to restart the application when running
the first time.

== Kitematic

server.website is not deployed to docker.io

== Docker.io

buildPipeine2.groovy does the following:

* ./gradlew skysail.server.website:export.website.docker
* ./gradlew skysail.server.website:runnable skysail.server.website:buildImage -Pversion=${env.BUILD_VERSION}
* /home/carsten/install/docker/skysail/run_docker.sh website test ${env.BUILD_VERSION} &

=== evandor.de

