@startuml
RoutesCreator -> ApplicationActor: ProcessCommand
ApplicationActor -> ControllerActor: SkysailContext
ControllerActor -> Resource: get(RequestEvent)

Resource --> ControllerActor
ControllerActor -> ApplicationActor
ApplicationActor -> RoutesCreator

@enduml