= all deployment / run modes

skysail projects can be started in a variety of ways:

== local IDE(s)

=== Intellij

Below you'll find instructions for both Intellij and Eclipse.

==== OSGi BND run configuration

Use the 'demo' bnd run configuration and start or debug it. Your
default browser should open at http://localhost:8082.

Configuration taken from /config/local

open issue: https://github.com/evandor/skysail-server/issues/4

==== docker run configuration

use the 'demo' docker run configuration
start, and open http://192.168.99.100:9102 (windows 7).
The actual host ip might be different on your system.

Configuration taken from /config/docker

=== Eclipse

to be done

== from jar file

./gradlew skysail.server.demo:export.demo
cd skysail.server.demo/generated/distributions/executable/
java -jar demo.jar

Configuration will be extracted from the contained server.demo.jar file
and put next to the demo.jar. You'll need to restart the application when running
the first time.

== Kitematic

server.demo is not deployed to docker.io

== Docker.io

TODO

buildPipeine2.groovy does the following:

* ./gradlew skysail.server.demo:export.demo.docker
* ./gradlew skysail.server.demo:runnable skysail.server.demo:buildImage -Pversion=${env.BUILD_VERSION}
* /home/carsten/install/docker/skysail/run_docker.sh demo test ${env.BUILD_VERSION} &

=== evandor.de

TODO
